### ISSUE TITLE
USERGUIDE.md is 404ing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-cli-toolkit#43] opened 2024-11-29 13:06 UTC
Small thing, but from the pypi page, when I click the link for the user guide, I get 404. The userguide here in gh seems to be fine.

https://pypi.org/project/hdx-cli-toolkit/USERGUIDE.md

**Comment by IanHopkinson** [comment] 2024-11-29 13:50
Yes, this is actually a duplicate of #40! I think I decided fixing the link wasn't worth a whole release. Maybe once you finished finding issues I'll do a little documentation/bugfix release.

**Comment by IanHopkinson** [comment] 2024-12-06 14:03
Resolved in #46

**Closed by IanHopkinson** 2024-12-06 14:03 UTC
